analyze_task:
  container:
    image: cirrusci/flutter:latest
  analyze_script:
    - flutter analyze

unit_test_task:
  container:
    image: cirrusci/flutter:latest
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - flutter test --coverage
    - lcov --list coverage/lcov.info
    # - genhtml coverage/lcov.info --output=coverage

ui_test_task:
  osx_instance:
    image: catalina-flutter
  pub_cache:
    folder: ~/.pub-cache
  environment:
    LTA_DATAMALL_API_KEY: ENCRYPTED[7c5c36fa21b1913320ef471077914da5f765a3a7b902e1d5224ade79635c6ee9b1842b2c677295a4094253a6587cb27b]
  ui_test_script:
    - xcrun simctl list
    - flutter drive --target=test_driver/app.dart --dart-define=IS_FLUTTER_DRIVE_RUN=true
