osx_instance:
  image: catalina-xcode-11.4.1-flutter

env:
  AUTH_TOKEN: ENCRYPTED[96e726ee10df063efb5cdd500da0ee8c0088e031eb8305a1b16239f791ab0758b7bc85b9661d7348493ee47e43c21392]

unit_test_task:
  flutter_version_check_script:
    - flutter --version
  create_env_script:
    - touch .env
    - echo "LTA_DATAMALL_KEY="${AUTH_TOKEN} > .env
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - flutter analyze
    - flutter test --coverage
    - lcov --list coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage

ui_test_task:
  create_env_script:
    - touch .env
    - echo "LTA_DATAMALL_KEY="${AUTH_TOKEN} > .env
  only_if: $BRANCH == "master"
  script:
    - ./execute_ui_tests.sh
  after_script:
    - echo "Delete simulator"
    - xcrun simctl delete iOS13TestDevice
