prepare_env_task: &PREPARE_ENV_TASK
  create_env_script:
    - echo "LTA_DATAMALL_KEY="ENCRYPTED[7c5c36fa21b1913320ef471077914da5f765a3a7b902e1d5224ade79635c6ee9b1842b2c677295a4094253a6587cb27b] > .env

analyze_task:
  <<: *PREPARE_ENV_TASK
  container:
    image: cirrusci/flutter:latest
  analyze_script:
    - flutter analyze

unit_test_task:
  <<: *PREPARE_ENV_TASK
  container:
    image: cirrusci/flutter:latest
    prepare_test_coverage_script:
      - ./prepare_test_coverage.sh lta_datamall_flutter
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - flutter test --coverage
    - lcov --list coverage/lcov.info
    # - genhtml coverage/lcov.info --output=coverage
# ui_test_task:
#   osx_instance:
#     image: catalina-flutter
#   only_if: $BRANCH == "master"
#   add_applesimutils_script:
#     - brew tap wix/brew
#     - brew install applesimutils
#   create_env_script:
#     - echo "LTA_DATAMALL_KEY="${AUTH_TOKEN} > .env
#   script:
#     - ./execute_ui_tests.sh
#   after_script:
#     - echo "Delete simulator"
#     - xcrun simctl delete iOS13TestDevice
