analyze_task:
  container:
    image: cirrusci/flutter:latest
  analyze_script:
    - flutter analyze

unit_test_task:
  container:
    image: cirrusci/flutter:latest
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - flutter test --coverage
    - lcov --list coverage/lcov.info
    # - genhtml coverage/lcov.info --output=coverage
# ui_test_task:
#   osx_instance:
#     image: catalina-flutter
#   only_if: $BRANCH == "master"
#   add_applesimutils_script:
#     - brew tap wix/brew
#     - brew install applesimutils
#   create_env_script:
#     - echo "LTA_DATAMALL_KEY="${AUTH_TOKEN} > .env
#   script:
#     - ./execute_ui_tests.sh
#   after_script:
#     - echo "Delete simulator"
#     - xcrun simctl delete iOS13TestDevice
