stages:
  - test

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - pwd
  - cd ios
  - bundle update --bundler
  - gem install bundler
  - bundle install

build_job:
  stage: test
  tags:
    - ios
  script:
    - fastlane test
  artifacts:
    expire_in: 90 days
    paths:
      - build
  only:
    - master
    - develop
    - feature/*
